version: "3.8"
services:
  server:
    build:
      context: ./server/
      dockerfile: Dockerfile
    container_name: server-express-graphql
    ports:
      - 80:80
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    command: "npm run start"
    depends_on:
      - database
  client:
    build:
      context: ./client/
      dockerfile: Dockerfile
    container_name: client-react
    ports:
      - 5173:5173
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    command: "npm run dev"
    depends_on:
      - server
  database:
    image: public.ecr.aws/docker/library/postgres:16
    ports:
      - 5432:5432
    volumes:
      - ./volumes/postgres:/var/lib/postgres/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: always
