version: "3.8"
services:
  server:
    build:
      context: ./server/
      dockerfile: Dockerfile
    container_name: server-express-graphql
    ports:
      - 80:80
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    command: "npm run dev"
  client:
    build:
      context: ./client/
      dockerfile: Dockerfile
    container_name: client-react
    ports:
      - 5173:5173
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    command: "npm run dev"
    depends_on:
      - server
